name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  solidity-unit-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        run: ./scripts/install_foundry.sh

      - name: Run unit tests
        run: |
          export PATH=$PATH:$HOME/.foundry/bin
          forge test -vvv

  go-unit-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repositories and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run Go unit tests
        run: |
          source scripts/constants.sh
          go test ./...

  teleporter_e2e:
    name: teleporter-e2e-tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repositories and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install Foundry
        run: ./scripts/install_foundry.sh

      - name: Run E2E Tests
        # Forge installs to BASE_DIR, but updates the PATH definition in $HOME/.bashrc
        run: |
          export PATH=$PATH:$HOME/.foundry/bin
          export PATH="$PATH:$GOPATH/bin"
          ./scripts/local/e2e_test.sh --component teleporter

      - name: Upload tmpnet network dir
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-tmpnet-data
          path: |
            ~/.tmpnet/networks
            ~/.tmpnet/prometheus/prometheus.log
            ~/.tmpnet/promtail/promtail.log
          if-no-files-found: error

  governance_e2e:
    name: governance-e2e-tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repositories and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install Foundry
        run: ./scripts/install_foundry.sh

      - name: Run E2E Tests
        # Forge installs to BASE_DIR, but updates the PATH definition in $HOME/.bashrc
        run: |
          export PATH=$PATH:$HOME/.foundry/bin
          export PATH="$PATH:$GOPATH/bin"
          ./scripts/local/e2e_test.sh --component governance

      - name: Upload tmpnet network dir
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-tmpnet-data
          path: |
            ~/.tmpnet/networks
            ~/.tmpnet/prometheus/prometheus.log
            ~/.tmpnet/promtail/promtail.log
          if-no-files-found: error

  validator_manager_e2e:
    name: validator-manager-e2e-tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repositories and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install Foundry
        run: ./scripts/install_foundry.sh

      - name: Run E2E Tests
        # Forge installs to BASE_DIR, but updates the PATH definition in $HOME/.bashrc
        run: |
          export PATH=$PATH:$HOME/.foundry/bin
          export PATH="$PATH:$GOPATH/bin"
          ./scripts/local/e2e_test.sh --component validator-manager

      - name: Upload tmpnet network dir
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-tmpnet-data
          path: |
            ~/.tmpnet/networks
            ~/.tmpnet/prometheus/prometheus.log
            ~/.tmpnet/promtail/promtail.log
          if-no-files-found: error